const complementarity = {
    "explorateur|plongeur":  {
                                 "pourquoi":  "Ces deux profils occupent les pôles opposés d\u0027un même axe : l\u0027Explorateur·rice Divergent·e multiplie les pistes, les associations et les hypothèses, tandis que le·la Plongeur·euse Analytique trie, vérifie et ancre dans les données factuelles. L\u0027un ouvre le champ des possibles, l\u0027autre referme sur ce qui tient solidement, de sorte que la créativité ne reste pas en l\u0027air et que la rigueur ne se prive pas de matière à examiner. Cette alternance entre divergence et convergence (Cropley, 2006) constitue justement le cycle complet dont une idée a besoin pour devenir une solution utilisable.",
                                 "frictions":  "L\u0027Explorateur·rice peut percevoir les questions du·de la Plongeur·euse comme un frein, un excès de prudence qui « tue » les idées avant qu\u0027elles aient mûri ; à l\u0027inverse, le·la Plongeur·euse peut juger ces idées trop floues, insuffisamment étayées, et se sentir bousculé·e par le rythme et l\u0027ambiguïté assumés de l\u0027autre. Le risque est alors une incompréhension de tempo : l\u0027un voudrait avancer large et vite, l\u0027autre approfondir et sécuriser, chacun lisant la posture de l\u0027autre comme un défaut plutôt que comme un apport.",
                                 "collaborer":  "Séquencez explicitement le travail : un temps d\u0027exploration où l\u0027Explorateur·rice fait foisonner les pistes sans censure, puis un temps d\u0027analyse où le·la Plongeur·euse les passe au crible des faits et de la faisabilité. Nommez à voix haute dans quelle phase vous êtes, pour que les questions critiques n\u0027arrivent pas trop tôt et que les idées nouvelles ne perturbent pas une vérification en cours. Convenez ensemble de critères simples de tri à la fin de chaque cycle, afin que l\u0027ouverture et la rigueur se passent le relais plutôt que de s\u0027opposer.",
                                 "developper":  {
                                                    "explorateur":  "Avant de présenter une idée, accordez-vous quelques minutes pour la confronter vous-même à deux ou trois faits ou contre-exemples, et notez ce qui la rendrait vérifiable. Vous gagnerez en crédibilité sans rien perdre de votre élan créatif.",
                                                    "plongeur":  "De temps en temps, autorisez-vous une courte phase où vous suspendez le jugement critique et listez plusieurs pistes, même imparfaites, avant de les évaluer. Cette parenthèse d\u0027ouverture peut révéler des options que la seule analyse aurait écartées trop tôt."
                                                }
                             },
    "architecte|plongeur":  {
                                "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se combinent bien : l\u0027Architecte Méthodique structure le « comment » et le « quand » (planification, organisation, fiabilité), tandis que le Plongeur·euse Analytique éclaire le « sur quelle base » (données factuelles, examen critique, pensée convergente). L\u0027un transforme l\u0027analyse en plan d\u0027action séquencé et tenable ; l\u0027autre vérifie que ce plan repose sur des faits solides plutôt que sur des routines. Ensemble, ils tendent à produire des décisions à la fois rigoureuses et exécutables (Kirton, 2003).",
                                "frictions":  "L\u0027Architecte peut percevoir le besoin de vérification du Plongeur·euse comme un ralentissement qui menace les échéances, et le Plongeur·euse peut vivre l\u0027attachement au plan comme une fermeture à des données nouvelles. Des tensions naissent aussi du rythme : avancer pour tenir le calendrier d\u0027un côté, suspendre le jugement le temps d\u0027analyser de l\u0027autre. Le malentendu fréquent est de confondre prudence analytique et lenteur, ou méthode et rigidité.",
                                "collaborer":  "Une répartition utile consiste à confier au Plongeur·euse l\u0027examen des données et la formulation des hypothèses en amont, puis à l\u0027Architecte la mise en plan, le séquencement et le suivi. Convenez ensemble de points de décision explicites où l\u0027analyse « nourrit » le plan, avec un délai d\u0027investigation borné pour respecter les échéances. Nommer clairement qui tranche et quand évite que la vérification et la planification ne se gênent (Edmondson, 2019).",
                                "developper":  {
                                                   "architecte":  "Avant de figer un plan, prenez l\u0027habitude de demander « sur quelles données repose cette étape ? » et réservez un court temps pour tester l\u0027hypothèse de départ plutôt que de l\u0027adopter par défaut.",
                                                   "plongeur":  "Une fois l\u0027analyse posée, traduisez-la en quelques étapes datées et hiérarchisées, en vous fixant une limite de temps d\u0027investigation afin que la décision puisse avancer."
                                               }
                            },
    "navigateur|plongeur":  {
                                "pourquoi":  "Ces deux profils relèvent d\u0027axes distincts et se renforcent plutôt qu\u0027ils ne s\u0027opposent : la Navigateur·rice perçoit vite une direction à partir de signaux faibles, là où le·la Plongeur·euse étaie, vérifie et structure cette intuition par les faits. C\u0027est la rencontre d\u0027une lecture rapide de la situation (proche de la décision intuitive décrite par Klein, 1998) et d\u0027une rigueur convergente fondée sur les données (Cropley, 2006). L\u0027un·e ouvre une piste dans l\u0027incertitude, l\u0027autre en éprouve la solidité, ce qui élargit l\u0027éventail des situations bien traitées.",
                                "frictions":  "La Navigateur·rice peut percevoir les demandes de preuves et de vérification comme un frein qui ralentit ou met en doute son ressenti, tandis que le·la Plongeur·euse peut vivre les décisions rapides « sans pièces au dossier » comme un manque de fondement. Le rythme diffère aussi : l\u0027un·e veut avancer et ajuster en chemin, l\u0027autre veut consolider avant d\u0027engager. Sans clarification, ces écarts se lisent à tort comme de la précipitation d\u0027un côté ou de la lenteur de l\u0027autre, alors qu\u0027il s\u0027agit de deux manières légitimes de traiter l\u0027information.",
                                "collaborer":  "Une répartition utile consiste à laisser la Navigateur·rice formuler les premières hypothèses et repérer les opportunités ou les signaux faibles, puis à confier au·à la Plongeur·euse leur examen critique et la consolidation factuelle avant l\u0027engagement. Convenez ensemble du moment où l\u0027on bascule de l\u0027exploration à la vérification, et de seuils simples (ce qui peut se décider vite, ce qui demande des données). Nommer explicitement que les deux apports comptent réduit le risque de lire la complémentarité comme une critique mutuelle.",
                                "developper":  {
                                                   "navigateur":  "Avant d\u0027agir sur une intuition forte, prenez l\u0027habitude de noter en une ligne le ou les signaux qui la fondent, puis de vous demander quelle donnée simple pourrait la confirmer ou l\u0027infirmer. Ce court temps d\u0027explicitation rend votre lecture partageable et vérifiable sans étouffer sa rapidité.",
                                                   "plongeur":  "Accordez-vous, dans les situations à faible enjeu ou très incertaines, le droit de poser une première orientation à partir de votre ressenti, quitte à l\u0027affiner ensuite avec les faits. S\u0027exercer à décider avec une information partielle développe l\u0027agilité utile quand les données manquent ou tardent."
                                               }
                            },
    "pilote|plongeur":  {
                            "pourquoi":  "Ces deux profils relèvent d\u0027axes différents qui se renforcent : le Pilote Orienté·e Tâche apporte le cap, le rythme et la clarté des objectifs, tandis que le Plongeur·euse Analytique apporte la profondeur, la vérification des données et l\u0027esprit critique. Là où l\u0027un fait avancer, l\u0027autre s\u0027assure que la direction repose sur des éléments solides, de sorte que la décision rapide gagne en justesse (Kahneman, 2011). Leur combinaison permet d\u0027allier efficacité d\u0027exécution et fiabilité du raisonnement, sans que l\u0027un prime sur l\u0027autre.",
                            "frictions":  "Le Pilote peut percevoir l\u0027exigence d\u0027analyse comme un frein qui retarde l\u0027action, tandis que le Plongeur peut vivre la pression des délais comme une incitation à bâcler la vérification. Ces malentendus tiennent souvent à des temporalités différentes : l\u0027un mesure la valeur à l\u0027avancement visible, l\u0027autre à la solidité du fondement. Sans dialogue explicite, chacun peut interpréter la prudence de l\u0027autre comme de la lenteur, ou son allant comme de la précipitation.",
                            "collaborer":  "Convenez ensemble, en amont, du niveau d\u0027analyse réellement nécessaire avant de décider, afin que la rigueur serve l\u0027objectif sans le bloquer. Le Pilote peut fixer le cadre, les priorités et les échéances, pendant que le Plongeur sécurise les points sensibles en signalant ce qui mérite vérification avant d\u0027agir. Réserver un temps court mais réel à l\u0027examen critique, puis trancher, permet de bénéficier des deux apports plutôt que de les opposer (Grant, 2021).",
                            "developper":  {
                                               "pilote":  "Avant de lancer une action, vous pouvez vous accorder une courte pause pour vérifier les deux ou trois données qui fondent vraiment votre décision, et formuler à voix haute la question « sur quoi repose ce choix ? ». Cette habitude ajoute une couche de solidité sans entamer votre rythme.",
                                               "plongeur":  "Vous pouvez vous fixer un moment précis où l\u0027analyse s\u0027arrête et où vous proposez une recommandation claire, même imparfaite, en distinguant ce qui est suffisamment établi pour avancer. Cela transforme votre rigueur en aide concrète à la décision et au respect des échéances."
                                           }
                        },
    "catalyseur|plongeur":  {
                                "pourquoi":  "Le ou la Catalyseur·rice Social·e veille à la qualité du lien, à la cohésion et au climat de confiance, tandis que le ou la Plongeur·euse Analytique apporte la rigueur, les faits et l\u0027examen critique des options. Comme ces deux profils relèvent d\u0027axes différents, ils se combinent plutôt qu\u0027ils ne s\u0027opposent : l\u0027un crée l\u0027espace humain où les idées peuvent s\u0027exprimer librement, l\u0027autre s\u0027assure qu\u0027elles tiennent à l\u0027épreuve des données. Un cadre relationnel sécurisant tend à favoriser l\u0027expression des désaccords utiles à une analyse solide (Edmondson, 2019).",
                                "frictions":  "Le profil analytique peut percevoir l\u0027attention portée au climat et aux émotions comme un détour qui retarde la décision, là où le profil relationnel peut vivre une critique factuelle, même bien intentionnée, comme un manque d\u0027égard pour les personnes. À l\u0027inverse, le souci de préserver l\u0027harmonie peut être ressenti comme un évitement des sujets qui fâchent, tandis que l\u0027exigence de preuves peut donner l\u0027impression de mettre la confiance en suspens. Ces malentendus tiennent souvent à des priorités différentes, non à un désaccord de fond.",
                                "collaborer":  "Vous pouvez vous répartir les rôles : la personne au profil relationnel ouvre l\u0027échange, recueille les points de vue et veille à ce que chacun se sente en sécurité pour parler, pendant que la personne au profil analytique structure les éléments factuels et teste la solidité des options. Convenez explicitement de moments distincts, l\u0027un pour faire émerger les idées et soigner le lien, l\u0027autre pour trancher sur la base des données, afin que ni l\u0027humain ni la rigueur ne soient sacrifiés. Nommer ensemble qui fait quoi évite que l\u0027analyse soit reçue comme une remise en cause des personnes.",
                                "developper":  {
                                                   "catalyseur":  "Avant une décision importante, vous pouvez vous accorder un temps pour lister calmement les faits disponibles et formuler une question critique simple, du type « qu\u0027est-ce qui pourrait nous contredire ? », afin d\u0027étayer l\u0027intuition relationnelle par quelques repères concrets.",
                                                   "plongeur":  "Avant de partager une analyse, vous pouvez prendre quelques instants pour reconnaître l\u0027effort ou le point de vue de vos interlocuteurs et formuler vos réserves comme une exploration commune plutôt qu\u0027un verdict, ce qui rend vos conclusions à la fois plus audibles et mieux reçues."
                                               }
                            },
    "pionnier|plongeur":  {
                              "pourquoi":  "Ces deux profils s\u0027appuient sur des axes différents et se renforcent : le Pionnier ouvre l\u0027espace des possibles, cherche la nouveauté et impulse le mouvement, tandis que le Plongeur creuse, vérifie et confronte les idées aux données factuelles. L\u0027élan du premier gagne en solidité quand il rencontre la rigueur critique du second, et l\u0027analyse du second prend de l\u0027air quand elle est aiguillonnée par de nouvelles pistes. Penser convergent et penser divergent forment ici un cycle utile plutôt qu\u0027une opposition (Cropley, 2006).",
                              "frictions":  "Le Pionnier peut percevoir le besoin de preuves et de vérifications du Plongeur comme un frein ou un manque d\u0027enthousiasme, là où il y voit surtout de la prudence. À l\u0027inverse, le Plongeur peut trouver les propositions du Pionnier prématurées ou insuffisamment étayées, et redouter qu\u0027on avance trop vite. Les rythmes diffèrent : l\u0027un veut explorer, l\u0027autre veut consolider, ce qui peut créer de l\u0027incompréhension sur le tempo et sur ce qui compte vraiment.",
                              "collaborer":  "Une répartition simple aide : le Pionnier ouvre la phase d\u0027idéation et formule les pistes nouvelles, le Plongeur les met ensuite à l\u0027épreuve des faits, des risques et des données disponibles. Convenez ensemble d\u0027un moment pour explorer librement, puis d\u0027un moment pour trier et valider, afin que chacun intervienne au bon stade sans se gêner. Verbaliser que la critique vise l\u0027idée et non la personne facilite des échanges francs et constructifs (Edmondson, 2019).",
                              "developper":  {
                                                 "pionnier":  "Avant de lancer une idée, prenez l\u0027habitude de noter une ou deux questions factuelles qu\u0027un esprit critique poserait (sur quoi est-ce que je m\u0027appuie ? qu\u0027est-ce qui pourrait ne pas marcher ?) et cherchez-y une réponse rapide.",
                                                 "plongeur":  "Réservez régulièrement un court temps où vous suspendez l\u0027évaluation pour explorer une option inhabituelle sans la juger tout de suite, simplement pour voir où elle mène."
                                             }
                          },
    "plongeur|stabilisateur":  {
                                   "pourquoi":  "Ces deux profils mobilisent des ressources cognitives qui se renforcent mutuellement : le Plongeur·euse Analytique creuse les données, questionne les hypothèses et cherche la rigueur du raisonnement (pensée convergente, esprit critique), tandis que le Stabilisateur·rice Prudent·e veille à la fiabilité, à la continuité et à l\u0027ancrage dans le réel de ce qui existe déjà. L\u0027un apporte la finesse de l\u0027examen critique, l\u0027autre la solidité de la mise en oeuvre durable ; ensemble, une analyse exigeante peut devenir une amélioration concrète qui tient dans la durée. Comme ils relèvent de deux axes différents, leur rencontre tient davantage de la combinaison de talents que de l\u0027affrontement de visions.",
                                   "frictions":  "Le Plongeur·euse peut percevoir la prudence du Stabilisateur·rice comme une résistance au changement ou un manque de remise en question, là où celui-ci protège en réalité la continuité du service. À l\u0027inverse, le Stabilisateur·rice peut trouver l\u0027analyse approfondie chronophage ou déstabilisante quand elle vient bousculer des pratiques éprouvées qui fonctionnent. Le malentendu naît souvent du rythme : l\u0027un veut comprendre à fond avant de trancher, l\u0027autre veut préserver un fonctionnement fiable sans le fragiliser.",
                                   "collaborer":  "Confiez au Plongeur·euse Analytique le diagnostic et l\u0027examen critique des options (vérification des données, mise à l\u0027épreuve des hypothèses), puis au Stabilisateur·rice Prudent·e la consolidation et le déploiement progressif de ce qui a été retenu. Posez ensemble, en amont, ce qui est négociable et ce qui doit rester stable, afin que l\u0027analyse serve l\u0027amélioration sans menacer la continuité. Nommer explicitement le moment où l\u0027on passe de l\u0027investigation à la sécurisation aide chacun à apporter sa force au bon instant.",
                                   "developper":  {
                                                      "plongeur":  "Avant de conclure une analyse, prenez un temps pour repérer ce qui fonctionne déjà bien dans l\u0027existant et pour évaluer concrètement l\u0027effort d\u0027adaptation que vos recommandations demanderont aux autres. Vous gagnerez en impact en formulant des améliorations progressives plutôt que des refontes globales.",
                                                      "stabilisateur":  "Face à une pratique établie, autorisez-vous à poser quelques questions factuelles (« sur quoi repose ce choix ? que disent les données ? ») avant de la reconduire par habitude. Cet examen ciblé n\u0027entame pas la fiabilité que vous valorisez : il en renforce le fondement."
                                                  }
                               },
    "architecte|explorateur":  {
                                   "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se combinent plutôt qu\u0027ils ne s\u0027opposent : l\u0027Architecte Méthodique structure et fiabilise l\u0027action quand l\u0027Explorateur·rice Divergent·e ouvre le champ des possibles en amont. L\u0027un apporte le cadre, l\u0027échéancier et la rigueur d\u0027exécution ; l\u0027autre alimente le projet en idées neuves et en angles inattendus, là où la seule planification tendrait à reproduire l\u0027existant (Cropley, 2006). Ensemble, ils couvrent à la fois le « quoi inventer » et le « comment le rendre réel ».",
                                   "frictions":  "L\u0027Architecte peut percevoir le foisonnement d\u0027idées comme une dispersion ou un risque pour les délais, tandis que l\u0027Explorateur·rice peut vivre la structuration comme un frein prématuré à sa créativité. Les divergences portent souvent sur le rythme : explorer largement avant de trancher, ou cadrer tôt pour sécuriser. Sans accord explicite, chacun peut sous-estimer la valeur du mode de l\u0027autre.",
                                   "collaborer":  "Séquencez le travail : laissez à l\u0027Explorateur·rice une phase d\u0027idéation ouverte, sans jugement ni contrainte de faisabilité, puis confiez à l\u0027Architecte la sélection, la structuration et la mise en œuvre des pistes retenues. Convenez ensemble de jalons clairs (quand on diverge, quand on converge) pour que l\u0027exploration nourrisse le plan sans le faire dériver. Une règle simple aide : on note toutes les idées, on en retient quelques-unes, on planifie celles-là.",
                                   "developper":  {
                                                      "architecte":  "Réservez-vous régulièrement de courts temps d\u0027exploration sans objectif d\u0027efficacité immédiate, où vous générez des options avant de les filtrer, pour vous entraîner à différer le tri et le jugement.",
                                                      "explorateur":  "Choisissez une de vos idées et offrez-lui un cadre minimal : une échéance, trois étapes concrètes, un premier livrable, afin d\u0027éprouver le plaisir de voir une intuition devenir réalité."
                                                  }
                               },
    "explorateur|navigateur":  {
                                   "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se renforcent mutuellement : l\u0027Explorateur·rice Divergent·e ouvre largement le champ des possibles et fait surgir des idées inattendues (Guilford, 1967 ; Cropley, 2006), tandis que le·la Navigateur·rice Intuitif·ive sent rapidement, dans l\u0027incertitude, lesquelles méritent d\u0027être suivies (Klein, 1998 ; Kahneman, 2011). L\u0027un·e élargit l\u0027espace des options, l\u0027autre y trace au plus vite un chemin praticable. Ensemble, vous combinez la richesse de la génération d\u0027idées et la vivacité de la lecture de terrain.",
                                   "frictions":  "L\u0027Explorateur·rice peut percevoir les décisions intuitives et rapides comme prématurées, fermant le champ avant qu\u0027il ait été pleinement déployé. À l\u0027inverse, le·la Navigateur·rice peut trouver la profusion d\u0027idées dispersante ou peu reliée aux signaux concrets du moment, et s\u0027impatienter d\u0027un foisonnement qui tarde à atterrir. Ces tensions tiennent à des rythmes et des appuis différents, non à un désaccord de fond.",
                                   "collaborer":  "Séquencez vos temps : laissez d\u0027abord l\u0027Explorateur·rice ouvrir et faire diverger les pistes sans filtre, puis appuyez-vous sur l\u0027intuition du·de la Navigateur·rice pour repérer celles qui résonnent avec le terrain et avancer. Rendez explicites les signaux faibles perçus et les critères de tri, afin que l\u0027élan intuitif reste lisible et discutable plutôt qu\u0027opaque (Edmondson, 2019). Convenez ensemble du moment où l\u0027on cesse d\u0027explorer pour décider.",
                                   "developper":  {
                                                      "explorateur":  "Fixez-vous parfois une contrainte de temps courte pour choisir une piste « suffisamment bonne » et l\u0027éprouver concrètement, plutôt que de chercher à épuiser toutes les options. Entraînez-vous à nommer la première impression qui vous vient face à une situation, avant de l\u0027élargir.",
                                                      "navigateur":  "Avant de trancher sur votre intuition, accordez-vous délibérément quelques minutes pour générer deux ou trois options alternatives, même improbables. Vous enrichirez ainsi votre lecture du terrain sans renoncer à votre rapidité de décision."
                                                  }
                               },
    "explorateur|pilote":  {
                               "pourquoi":  "L\u0027Explorateur·rice Divergent·e élargit le champ des possibles en générant des idées et en explorant l\u0027ambiguïté, là où le·la Pilote Orienté·e Tâche resserre ce champ en clarifiant les objectifs, les priorités et les délais (Cropley, 2006). Comme ces profils relèvent de deux axes différents, ils se combinent plutôt qu\u0027ils ne s\u0027opposent : l\u0027un ouvre, l\u0027autre convertit en plan d\u0027action concret. Ensemble, ils couvrent un cycle utile, de la divergence créative à la livraison structurée, chacun comblant un angle mort de l\u0027autre.",
                               "frictions":  "Le·la Pilote peut percevoir la phase d\u0027exploration comme une dispersion ou une perte de temps face à l\u0027échéance, tandis que l\u0027Explorateur·rice peut vivre le cadrage serré comme une fermeture prématurée des pistes. Les malentendus naissent souvent du rythme : besoin de converger vite d\u0027un côté, envie de laisser mûrir l\u0027ambiguïté de l\u0027autre. Sans accord explicite, l\u0027un peut se sentir bridé et l\u0027autre freiné dans l\u0027avancement.",
                               "collaborer":  "Séparez clairement les temps : une phase ouverte où l\u0027Explorateur·rice fait diverger les options sans jugement, puis une phase de décision où le·la Pilote arbitre, fixe le cap et les délais. Convenez ensemble d\u0027un point de bascule (« à telle date, on choisit ») pour que l\u0027exploration ait de l\u0027air sans menacer l\u0027échéance. Le·la Pilote peut traduire les idées retenues en jalons concrets, et l\u0027Explorateur·rice peut rester disponible pour rouvrir une piste si un obstacle apparaît.",
                               "developper":  {
                                                  "explorateur":  "Vous pouvez vous fixer vous-même un point d\u0027atterrissage pour vos idées : à un moment convenu, retenez deux ou trois pistes et formulez-les en prochaines étapes datées. Cela protège votre créativité tout en la rendant exploitable par l\u0027équipe.",
                                                  "pilote":  "Vous pouvez réserver, en amont d\u0027une décision, un court temps explicitement « sans verdict » pour laisser émerger des options auxquelles vous n\u0027auriez pas pensé spontanément. Quelques minutes d\u0027ouverture avant de cadrer enrichissent souvent le résultat sans menacer le délai."
                                              }
                           },
    "catalyseur|explorateur":  {
                                   "pourquoi":  "Ces deux profils opèrent sur des axes différents et se renforcent : l\u0027un travaille la qualité du lien et le sentiment de sécurité dans le groupe, l\u0027autre fait jaillir des idées nouvelles et explore des pistes inattendues. Le Catalyseur·rice crée le climat de confiance qui permet aux propositions audacieuses d\u0027être entendues sans crainte, tandis que l\u0027Explorateur·rice apporte la matière créative qui nourrit les échanges et empêche le collectif de tourner en rond. Un environnement où l\u0027on se sent en sécurité favorise d\u0027ailleurs la prise de parole et l\u0027expression d\u0027idées risquées (Edmondson, 2019), ce que la créativité divergente sait justement alimenter (Guilford, 1967).",
                                   "frictions":  "Le foisonnement d\u0027idées et le goût de l\u0027ambiguïté de l\u0027Explorateur·rice peuvent sembler déstabilisants au Catalyseur·rice, soucieux·se que chacun·e reste embarqué·e et que le groupe ne se disperse pas. À l\u0027inverse, l\u0027attention portée au consensus et au confort relationnel peut être vécue par l\u0027Explorateur·rice comme un frein qui bride les pistes les plus originales avant qu\u0027elles aient pu être explorées. Le malentendu naît souvent ici : l\u0027un·e perçoit un manque de cadre relationnel, l\u0027autre une pression à se conformer.",
                                   "collaborer":  "Une répartition utile consiste à laisser l\u0027Explorateur·rice ouvrir largement le champ des possibles en début de réflexion, pendant que le Catalyseur·rice veille à ce que chacun·e puisse contribuer et se sente entendu·e. Il est précieux de distinguer explicitement les temps de divergence (où toutes les idées sont bienvenues, sans jugement) des temps de convergence où le groupe choisit et s\u0027aligne (Cropley, 2006). Le Catalyseur·rice peut ainsi protéger l\u0027espace d\u0027exploration tout en ramenant le collectif vers une décision partagée et acceptée de tous.",
                                   "developper":  {
                                                      "catalyseur":  "Vous pourriez vous accorder, lors de certaines réunions, un temps où aucune idée n\u0027est évaluée ni mise au vote, simplement pour explorer des pistes inhabituelles sans chercher tout de suite l\u0027accord du groupe. S\u0027autoriser à reconsidérer une option déjà tranchée, plutôt que de la verrouiller pour préserver l\u0027harmonie, ouvre souvent des perspectives utiles (Grant, 2021).",
                                                      "explorateur":  "Vous pourriez prendre l\u0027habitude, avant de lancer une idée nouvelle, de vous demander qui dans le groupe risque de se sentir laissé·e de côté, et de formuler vos propositions de façon à inviter les autres à les enrichir. Vérifier que chacun·e a pu s\u0027exprimer renforce la qualité collective des échanges (Woolley et al., 2010)."
                                                  }
                               },
    "explorateur|pionnier":  {
                                 "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se renforcent mutuellement plutôt qu\u0027ils ne s\u0027opposent : l\u0027Explorateur·rice Divergent·e fait jaillir un large éventail d\u0027idées et joue avec l\u0027ambiguïté (Guilford, 1967), tandis que le·la Pionnier·ère Adaptatif·ive transforme cette matière foisonnante en mouvement concret vers la nouveauté. Ensemble, ils couvrent à la fois l\u0027amont créatif et l\u0027élan de mise en oeuvre du changement, ce qui peut nourrir une réflexion d\u0027équipe plus riche (Woolley et al., 2010).",
                                 "frictions":  "Le·la Pionnier·ère peut s\u0027impatienter devant des idées qui restent ouvertes ou non tranchées, et vouloir avancer avant que l\u0027exploration ne soit aboutie ; à l\u0027inverse, l\u0027Explorateur·rice peut vivre cette poussée vers l\u0027action comme une fermeture prématurée du champ des possibles. Le malentendu typique : l\u0027un croit qu\u0027on tourne en rond, l\u0027autre qu\u0027on referme trop tôt une piste prometteuse.",
                                 "collaborer":  "Vous pouvez séquencer vos forces : l\u0027Explorateur·rice ouvre largement le champ des options et fait émerger des pistes inattendues, puis le·la Pionnier·ère sélectionne ce qui mérite d\u0027être expérimenté et porte la dynamique de mise en mouvement. Convenez ensemble d\u0027un moment où l\u0027on bascule de la divergence vers l\u0027action, pour que personne ne se sente ni bridé ni bousculé, et préservez un espace où exprimer les doutes (Edmondson, 2019).",
                                 "developper":  {
                                                    "explorateur":  "Vous pourriez, après une phase d\u0027idéation, vous fixer un petit pas concret à tester rapidement, en transformant une de vos pistes en micro-expérimentation plutôt qu\u0027en idée laissée ouverte.",
                                                    "pionnier":  "Avant de vous lancer dans le changement, vous pourriez vous accorder un temps délibéré pour faire émerger plusieurs options, y compris inhabituelles, afin de ne pas vous engager trop vite sur la première piste séduisante."
                                                }
                             },
    "explorateur|stabilisateur":  {
                                      "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se nourrissent l\u0027un l\u0027autre plutôt que de s\u0027opposer : l\u0027Explorateur·rice Divergent·e élargit le champ des possibles, multiplie les idées et apprivoise l\u0027ambiguïté, là où le·la Stabilisateur·rice Prudent·e éprouve la solidité de ces idées, les ancre dans l\u0027existant et veille à leur continuité. L\u0027un ouvre, l\u0027autre consolide, si bien que l\u0027imagination ne reste pas sans suite et que la fiabilité ne se fige pas. Cette tension féconde entre génération et tri fait écho à la complémentarité entre styles innovateur et adaptatif décrite par Kirton (2003).",
                                      "frictions":  "Le·la Stabilisateur·rice peut percevoir le flot d\u0027idées de l\u0027Explorateur·rice comme dispersé ou risqué, tandis que celui-ci ou celle-ci peut vivre la prudence de l\u0027autre comme un frein ou un manque d\u0027audace. Les malentendus naissent souvent du rythme et du critère : l\u0027un valorise la quantité d\u0027options et le mouvement, l\u0027autre la sûreté du chemin déjà éprouvé. Sans clarté sur le moment où l\u0027on explore et celui où l\u0027on stabilise, chacun peut se sentir incompris.",
                                      "collaborer":  "Séquencez les temps : confiez à l\u0027Explorateur·rice les phases d\u0027ouverture et de génération d\u0027options, puis au·à la Stabilisateur·rice le tri, la mise en œuvre fiable et la pérennisation. Convenez ensemble de critères simples pour décider quelles idées passent à l\u0027épreuve du réel, afin que la sélection ne soit ni un veto ni une fuite en avant. Rendez explicite, pour chaque sujet, si l\u0027on est en mode « on cherche » ou « on consolide », pour que les deux apports trouvent leur place.",
                                      "developper":  {
                                                         "explorateur":  "Avant de lancer une nouvelle idée, prenez l\u0027habitude de noter une ou deux conditions concrètes de faisabilité et un premier petit pas réaliste. Vous gagnerez à choisir, parmi vos pistes, celle que vous menez jusqu\u0027au bout plutôt que d\u0027en ouvrir une de plus.",
                                                         "stabilisateur":  "De temps en temps, accordez-vous un temps court et sans enjeu pour imaginer plusieurs façons de faire avant de retenir l\u0027option la plus sûre. Vous pouvez aussi accueillir une idée inhabituelle en l\u0027essayant à petite échelle, comme une expérimentation réversible plutôt qu\u0027un engagement définitif."
                                                     }
                                  },
    "architecte|navigateur":  {
                                  "pourquoi":  "Ces deux profils occupent les pôles opposés du même axe « Processus d\u0027action » : là où l\u0027Architecte Méthodique sécurise par la planification, la structure et l\u0027anticipation, le·la Navigateur·rice Intuitif·ive avance par lecture rapide des signaux faibles et décision dans l\u0027incertitude (Kahneman, 2011, Système 1 vs Système 2). Leur complémentarité tient à cette tension : l\u0027un transforme l\u0027intuition en plan fiable et reproductible, l\u0027autre garde le cap quand le plan rencontre l\u0027imprévu. Ensemble, ils couvrent à la fois le besoin de cadre et celui d\u0027adaptation, ce qu\u0027aucun ne ferait aussi bien seul.",
                                  "frictions":  "L\u0027Architecte peut percevoir les décisions rapides du·de la Navigateur·rice comme précipitées ou peu étayées, tandis que ce dernier·ère peut vivre la demande de procédures et de garanties comme un frein qui ralentit l\u0027action. Les malentendus naissent souvent du rythme et du registre de preuve : « montre-moi le plan » d\u0027un côté, « on verra en avançant » de l\u0027autre. Sans explicitation, chacun peut interpréter la différence comme un manque de sérieux ou un manque de souplesse, alors qu\u0027il s\u0027agit de deux manières légitimes d\u0027agir.",
                                  "collaborer":  "Une répartition utile consiste à laisser le·la Navigateur·rice ouvrir et cadrer rapidement les situations incertaines ou urgentes, puis à confier à l\u0027Architecte la consolidation, la mise en procédure et le suivi dans la durée. Convenez ensemble d\u0027un seuil simple : quand peut-on décider vite, et quand faut-il un plan formalisé. Verbaliser le « pourquoi » de chaque mode, plutôt que de le subir, transforme l\u0027écart en relais plutôt qu\u0027en bras de fer.",
                                  "developper":  {
                                                     "architecte":  "Vous pouvez vous accorder, sur de petits enjeux réversibles, des décisions prises sur la base d\u0027une information suffisante mais incomplète, sans attendre le plan complet, en notant ensuite ce que votre première impression avait bien capté. Cela entraîne progressivement votre confiance dans la lecture rapide des situations.",
                                                     "navigateur":  "Vous pouvez prendre l\u0027habitude, après une décision intuitive, de poser en quelques lignes les étapes et les points de vigilance, afin de la rendre transmissible et de sécuriser le suivi. Ce léger formalisme, ciblé sur les sujets à enjeu, renforce l\u0027effet de vos intuitions sans en brider la vivacité."
                                                 }
                              },
    "architecte|pilote":  {
                              "pourquoi":  "Ces deux profils se situent sur des axes différents et se renforcent mutuellement : l\u0027Architecte Méthodique apporte la structure, l\u0027anticipation et la fiabilité d\u0027un plan solide, tandis que le Pilote Orienté tâche apporte le cap, la priorisation des résultats et la tenue des délais. Là où l\u0027un sécurise le « comment » et prévient les pertes de coordination (Steiner, 1972), l\u0027autre clarifie le « quoi » et le « pour quand », ce qui transforme une planification rigoureuse en avancée concrète. Ensemble, ils peuvent convertir une intention en exécution maîtrisée sans sacrifier ni la qualité ni l\u0027échéance.",
                              "frictions":  "Le Pilote peut percevoir la planification détaillée comme un ralentissement et pousser à agir avant que tout soit cadré, tandis que l\u0027Architecte peut vivre la pression sur les délais comme une mise en danger de la qualité ou de la rigueur. Des malentendus surgissent aussi sur le rythme : ce qui ressemble à de la prudence pour l\u0027un peut sembler de la lenteur pour l\u0027autre, et inversement la fermeté sur les objectifs peut être ressentie comme de la précipitation.",
                              "collaborer":  "Une répartition simple aide beaucoup : le Pilote fixe les objectifs, les priorités et les échéances, et l\u0027Architecte conçoit le chemin, les étapes et les points de contrôle qui les rendent atteignables. Convenez ensemble d\u0027un niveau de détail « suffisant pour démarrer » et de jalons partagés, afin de ne planifier ni trop ni trop peu. Réservez de courts points réguliers pour aligner cap et plan, ce qui limite les frictions et entretient une réelle clarté commune.",
                              "developper":  {
                                                 "architecte":  "En tant qu\u0027Architecte Méthodique, vous pouvez vous fixer une échéance explicite et un objectif de résultat dès le début d\u0027une tâche, puis vous autoriser à lancer avec un plan « assez bon » quitte à l\u0027ajuster en cours de route.",
                                                 "pilote":  "En tant que Pilote Orienté tâche, vous pouvez accorder quelques minutes en amont à cartographier les étapes et les points de contrôle, ce qui sécurise l\u0027atteinte du résultat sans freiner votre élan vers les délais."
                                             }
                          },
    "architecte|catalyseur":  {
                                  "pourquoi":  "Ces deux profils mobilisent des leviers différents et souvent complémentaires : l\u0027Architecte Méthodique structure l\u0027action (planification, fiabilité, organisation), tandis que la Catalyseur·rice Social·e prend soin du lien et du climat (cohésion, médiation, sécurité psychologique). L\u0027un apporte le cadre et la prévisibilité qui sécurisent le collectif, l\u0027autre apporte la confiance et l\u0027engagement sans lesquels le meilleur plan reste lettre morte. Un climat où chacun ose parler tend d\u0027ailleurs à soutenir l\u0027efficacité collective (Edmondson, 2019), et la coordination des compétences pèse autant que les compétences elles-mêmes (Woolley et al., 2010).",
                                  "frictions":  "L\u0027Architecte Méthodique peut percevoir l\u0027attention portée aux relations comme une digression qui ralentit l\u0027avancée, là où la Catalyseur·rice Social·e peut vivre un cadrage serré comme une rigidité qui étouffe les échanges. De son côté, l\u0027Architecte Méthodique peut trouver les processus trop centrés sur les personnes au détriment des tâches, tandis que la Catalyseur·rice Social·e peut juger le climat trop chaleureux pour que les engagements soient tenus. Ces malentendus relèvent souvent d\u0027une différence de priorités, non d\u0027un désaccord de fond.",
                                  "collaborer":  "Une répartition simple aide : laissez l\u0027Architecte Méthodique poser le cadre, le calendrier et les points de contrôle, et confiez à la Catalyseur·rice Social·e l\u0027animation des échanges, la circulation de la parole et la régulation des tensions. Convenez ensemble de moments distincts : un temps pour décider du « comment » et de l\u0027organisation, un autre pour s\u0027assurer que chacun se sente écouté et embarqué. Nommer explicitement ces deux besoins évite que l\u0027un se sente bousculé par l\u0027autre.",
                                  "developper":  {
                                                     "architecte":  "Réservez quelques minutes en début ou en fin de réunion pour prendre le pouls du groupe et inviter les retours, avant d\u0027entrer dans le plan d\u0027action. Vous découvrirez que prendre soin du lien fiabilise aussi les engagements que vous tenez tant à voir respectés.",
                                                     "catalyseur":  "Traduisez les élans et les décisions du groupe en quelques jalons concrets, avec qui fait quoi et pour quand, notés noir sur blanc. Ce minimum de structure protège la confiance que vous construisez, en évitant que de bonnes intentions ne restent sans suite."
                                                 }
                              },
    "architecte|pionnier":  {
                                "pourquoi":  "Ces deux profils relèvent d\u0027axes distincts (le rapport à l\u0027action pour l\u0027un, le rapport à la nouveauté pour l\u0027autre) et se combinent plutôt qu\u0027ils ne s\u0027opposent : le Pionnier ouvre des pistes et remet en question l\u0027existant, là où l\u0027Architecte les éprouve, les structure et les rend fiables dans la durée. Ce que l\u0027un explore en divergence, l\u0027autre tend à le faire converger vers une mise en œuvre tenable (Cropley, 2006), de sorte que l\u0027élan d\u0027innovation rencontre la rigueur de l\u0027exécution. Aucun des deux fonctionnements n\u0027est préférable : leur valeur tient justement à leur complémentarité.",
                                "frictions":  "Le Pionnier peut percevoir la planification de l\u0027Architecte comme un frein, tandis que l\u0027Architecte peut vivre les changements rapides comme une source de désordre ou de risque mal maîtrisé. S\u0027y ajoute un décalage de tempo : l\u0027un veut lancer pour apprendre en avançant, l\u0027autre veut cadrer avant de s\u0027engager. Sans dialogue explicite sur ces préférences, chacun peut prêter à l\u0027autre une intention qu\u0027il n\u0027a pas (résistance contre rigidité), alors qu\u0027il s\u0027agit surtout de deux manières légitimes d\u0027aborder l\u0027incertitude (Kirton, 2003).",
                                "collaborer":  "Une répartition utile consiste à confier au Pionnier la phase d\u0027exploration et de génération d\u0027options, puis à l\u0027Architecte la phase de cadrage, de fiabilisation et de suivi, en posant ensemble un point de bascule clair entre les deux. Convenez à l\u0027avance de ce qui reste ouvert à l\u0027expérimentation et de ce qui exige un cadre stable, pour que ni l\u0027élan ni la rigueur ne soient vécus comme une intrusion. Nommer ces préférences sans en faire un reproche crée un climat où chacun ose contribuer (Edmondson, 2019).",
                                "developper":  {
                                                   "architecte":  "Architecte Méthodique, vous pouvez réserver de petits espaces d\u0027expérimentation à faible enjeu (un test limité dans le temps, une version « brouillon » assumée) où l\u0027objectif est d\u0027explorer plutôt que de finaliser, en vous autorisant à reporter l\u0027évaluation à la fin de l\u0027essai.",
                                                   "pionnier":  "Pionnier·ère Adaptatif·ive, vous gagnez à formaliser ne serait-ce qu\u0027une étape minimale avant de lancer une idée : noter l\u0027objectif, qui est concerné et un premier jalon, afin que la nouveauté devienne plus facile à reprendre et à transmettre."
                                               }
                            },
    "architecte|stabilisateur":  {
                                     "pourquoi":  "Ce duo associe deux logiques distinctes : l\u0027Architecte Méthodique structure l\u0027action dans le temps (anticiper, planifier, organiser), tandis que le ou la Stabilisateur·rice Prudent·e veille à la solidité et à la continuité de ce qui existe déjà. L\u0027un trace la feuille de route, l\u0027autre s\u0027assure qu\u0027elle tienne dans la durée et ne fragilise pas les acquis ; ensemble, ils transforment une intention en dispositif à la fois ordonné et durable. Cette combinaison fait écho à la posture d\u0027adaptation décrite par Kirton (2003), où l\u0027on cherche à améliorer et fiabiliser l\u0027existant plutôt qu\u0027à tout reconstruire.",
                                     "frictions":  "Une tension peut naître autour du rythme : l\u0027Architecte peut percevoir la prudence de l\u0027autre comme un frein qui retarde le plan, et le ou la Stabilisateur·rice peut vivre la planification ambitieuse comme une pression qui néglige la réalité du terrain. Le premier raisonne souvent en projection et en jalons à venir, le second en consolidation de l\u0027existant, ce qui crée des malentendus sur le moment opportun d\u0027avancer. Sans dialogue, chacun peut juger l\u0027autre soit trop pressé, soit trop attentiste, alors que les deux cherchent la même fiabilité.",
                                     "collaborer":  "Confiez à l\u0027Architecte Méthodique la conception du plan, la définition des étapes et des échéances, et au ou à la Stabilisateur·rice Prudent·e l\u0027évaluation de la faisabilité concrète et la sécurisation des acquis avant chaque avancée. Prévoyez un temps d\u0027échange où le plan est confronté au terrain : ce qui peut être consolidé, ce qui mérite d\u0027être testé prudemment. Nommer explicitement ces rôles évite que le souci de structure et le souci de stabilité soient lus comme des reproches mutuels.",
                                     "developper":  {
                                                        "architecte":  "Avant de dérouler votre plan, prenez le temps d\u0027inventorier ce qui fonctionne déjà et d\u0027intégrer une étape de consolidation, plutôt que de tout reconstruire ; demandez-vous ce qui mérite d\u0027être préservé autant que ce qui doit être organisé.",
                                                        "stabilisateur":  "Pour gagner en visibilité, traduisez votre attention au terrain en quelques jalons et échéances explicites, afin que votre prudence devienne une étape lisible du plan plutôt qu\u0027une réserve perçue comme un frein."
                                                    }
                                 },
    "navigateur|pilote":  {
                              "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se combinent bien : la Navigatrice ou le Navigateur lit vite les signaux faibles et décide dans l\u0027incertitude (proche de la décision intuitive décrite par Klein, 1998), tandis que la Pilote ou le Pilote transforme ces lectures en objectifs clairs, en résultats et en délais tenus (Blake \u0026 Mouton, 1964). L\u0027un·e apporte la souplesse et le flair de terrain quand les données manquent, l\u0027autre apporte la structure et le cap qui rendent ces intuitions exploitables. Ensemble, vous reliez la perception rapide d\u0027une situation à son exécution rigoureuse.",
                              "frictions":  "La Pilote ou le Pilote peut demander des justifications explicites là où la Navigatrice ou le Navigateur ressent sans toujours pouvoir verbaliser, ce qui peut donner une impression de flou d\u0027un côté et de rigidité de l\u0027autre. À l\u0027inverse, le souci des délais et du livrable peut sembler couper court à une exploration encore utile, tandis que l\u0027agilité intuitive peut paraître désorganisée ou imprévisible. Ces tensions tiennent à deux rythmes et deux langages, non à un manque de compétence de part et d\u0027autre.",
                              "collaborer":  "Laissez la Navigatrice ou le Navigateur cadrer tôt la lecture de situation et alerter sur les signaux faibles, puis confiez à la Pilote ou au Pilote la mise en objectifs, le séquençage et le suivi des échéances. Convenez d\u0027un moment court où l\u0027intuition est mise en mots avant d\u0027être traduite en plan, pour que chacun·e comprenne le raisonnement de l\u0027autre. Réservez une marge explicite pour ajuster le cap si de nouveaux signaux apparaissent en cours de route.",
                              "developper":  {
                                                 "navigateur":  "Entraînez-vous à formuler en une phrase l\u0027objectif visé et le délai avant de vous lancer, et notez après coup ce qui a confirmé ou infirmé votre intuition pour la rendre partageable.",
                                                 "pilote":  "Avant de figer le plan, accordez-vous un temps court pour écouter les signaux faibles et garder une option ouverte, en acceptant qu\u0027une lecture de terrain encore non chiffrée puisse être précieuse (Klein, 1998)."
                                             }
                          },
    "catalyseur|navigateur":  {
                                  "pourquoi":  "Ces deux profils relèvent d\u0027axes différents et se combinent plus qu\u0027ils ne s\u0027opposent : le ou la Catalyseur·rice Social·e travaille la qualité du lien et la sécurité du collectif, là où le ou la Navigateur·rice Intuitif·ive lit vite les signaux faibles et tranche dans l\u0027incertitude (Klein, 1998). L\u0027un·e crée le climat où l\u0027intuition de l\u0027autre peut s\u0027exprimer sans être balayée, et l\u0027autre apporte une capacité de décision rapide quand le groupe hésite. Ensemble, ils relient le « comment on se parle » et le « comment on agit vite », ce qui peut limiter certaines pertes de coordination en équipe (Steiner, 1972).",
                                  "frictions":  "Le ou la Catalyseur·rice peut vivre les décisions rapides et peu explicitées comme un passage en force qui court-circuite le groupe, tandis que le ou la Navigateur·rice peut trouver la recherche de consensus lente ou diluante. À l\u0027inverse, une intuition exprimée sans justification peut sembler arbitraire à qui valorise l\u0027écoute et l\u0027inclusion de chacun·e. Ces tensions tiennent souvent à des rythmes et des besoins d\u0027explicitation différents, pas à un défaut de l\u0027un·e ou de l\u0027autre.",
                                  "collaborer":  "Une répartition utile : confiez au ou à la Navigateur·rice la lecture rapide de la situation et la première hypothèse de décision, et au ou à la Catalyseur·rice le soin de la rendre audible, de recueillir les objections et de maintenir la cohésion. Convenez ensemble de moments où l\u0027on décide vite et de moments où l\u0027on prend le temps d\u0027embarquer le collectif, pour que la rapidité ne se paie pas en adhésion. Instaurer un climat où l\u0027on peut nommer un doute sans crainte aide les deux modes à se nourrir (Edmondson, 2019).",
                                  "developper":  {
                                                     "catalyseur":  "Vous pouvez vous autoriser, dans des situations à faible enjeu, à formuler une première intuition rapide avant d\u0027avoir consulté tout le monde, puis à l\u0027ajuster ensuite. Cela entraîne votre confiance dans une lecture immédiate sans renoncer à votre attention au groupe.",
                                                     "navigateur":  "Vous pouvez prendre l\u0027habitude de rendre votre intuition un peu plus explicite, en disant en une phrase ce qui vous met sur cette piste, pour que les autres se sentent associés. Vérifier brièvement comment chacun·e reçoit la décision renforce l\u0027adhésion sans freiner votre rapidité."
                                                 }
                              },
    "navigateur|pionnier":  {
                                "pourquoi":  "Ces deux profils relèvent d\u0027axes distincts et se combinent plutôt qu\u0027ils ne s\u0027opposent : le Pionnier ouvre des pistes nouvelles et provoque le changement, tandis que le Navigateur, fort de son intuition experte (Système 1), sait avancer vite et lire les signaux faibles dans l\u0027incertitude que ces nouveautés créent (Kahneman, 2011 ; Klein, 1998). L\u0027un élargit le champ des possibles, l\u0027autre transforme ces possibles en décisions concrètes et incarnées sur le terrain. Ensemble, ils relient l\u0027élan exploratoire à une capacité d\u0027action rapide et située.",
                                "frictions":  "Le Pionnier peut percevoir le Navigateur comme attaché à ce qui marche déjà, trop ancré dans l\u0027expérience du terrain, là où lui cherche à renouveler ; le Navigateur peut trouver que le Pionnier multiplie les nouveautés sans toujours mesurer comment elles atterrissent dans le réel. Leurs rythmes diffèrent aussi : envie d\u0027explorer largement d\u0027un côté, besoin de décider et d\u0027agir maintenant de l\u0027autre. Ces écarts, mal nommés, peuvent se lire comme de la résistance ou de la dispersion alors qu\u0027il s\u0027agit de logiques complémentaires.",
                                "collaborer":  "Laissez le Pionnier ouvrir et cadrer les pistes nouvelles, puis appuyez-vous sur le Navigateur pour sentir rapidement lesquelles tiennent au contact du réel et engager les premiers pas. Convenez ensemble d\u0027un temps court d\u0027exploration avant de basculer en mode décision, et explicitez vos intuitions à voix haute pour qu\u0027elles deviennent un appui partagé plutôt qu\u0027un point de friction (Edmondson, 2019). Le Pionnier nourrit le « pourquoi changer », le Navigateur sécurise le « comment avancer dès maintenant ».",
                                "developper":  {
                                                   "navigateur":  "Réservez-vous régulièrement de courts moments pour interroger une habitude qui vous semble évidente et tester une variante, même mineure, avant de la trancher à l\u0027intuition. Cela élargit votre répertoire sans renoncer à votre rapidité d\u0027action (Grant, 2021).",
                                                   "pionnier":  "Quand une piste nouvelle vous emballe, accordez-vous un essai concret et rapide sur le terrain plutôt qu\u0027une exploration prolongée, et appuyez-vous sur les signaux observables des premiers retours pour ajuster (Klein, 1998). Vous gagnerez en ancrage sans perdre votre goût du renouvellement."
                                               }
                            },
    "navigateur|stabilisateur":  {
                                     "pourquoi":  "Ces deux profils relèvent d\u0027axes distincts et se nourrissent l\u0027un l\u0027autre plutôt que de s\u0027opposer : le ou la Navigateur·rice Intuitif·ive capte vite les signaux faibles et tranche dans l\u0027incertitude (proche de la décision intuitive experte décrite par Klein, 1998), tandis que le ou la Stabilisateur·rice Prudent·e ancre ces élans dans la durée, fiabilise et optimise l\u0027existant. L\u0027un ouvre des pistes et accélère, l\u0027autre éprouve leur solidité et les rend tenables dans le temps. Ensemble, ils couvrent à la fois la réactivité face à l\u0027imprévu et la continuité du soin au quotidien.",
                                     "frictions":  "Le ou la Navigateur·rice peut percevoir la prudence comme un frein ou une lenteur, là où le ou la Stabilisateur·rice peut vivre les décisions rapides comme un manque de cadrage ou un risque pour la continuité. Le premier raisonne souvent par ressenti global difficile à expliciter, ce qui peut laisser le second sans les repères concrets dont il a besoin pour s\u0027engager sereinement. Sans dialogue, chacun peut interpréter la posture de l\u0027autre comme un jugement sur sa façon de travailler.",
                                     "collaborer":  "Confiez au ou à la Navigateur·rice l\u0027exploration initiale et les situations mouvantes, et au ou à la Stabilisateur·rice la consolidation, le suivi et la mise en routine de ce qui fonctionne. Convenez d\u0027un rituel simple où l\u0027intuition est exposée puis questionnée à voix haute, afin que la prudence travaille la piste sans la bloquer. Nommez ensemble, en amont, ce qui relève de l\u0027urgence (on tranche vite) et ce qui relève de la durée (on sécurise), pour éviter que les rythmes ne s\u0027opposent.",
                                     "developper":  {
                                                        "navigateur":  "Prenez l\u0027habitude, après une décision rapide, de noter en une ligne ce qui vous a alerté et de prévoir un point de vérification ultérieur. Vous gardez votre vitesse tout en offrant des repères concrets et une trace utile à la continuité.",
                                                        "stabilisateur":  "Autorisez-vous, sur un périmètre limité et réversible, à suivre une première impression sans attendre toutes les garanties, puis observez ce qu\u0027elle révèle. Vous élargissez ainsi votre marge d\u0027action face à l\u0027imprévu sans renoncer à votre exigence de fiabilité."
                                                    }
                                 },
    "catalyseur|pilote":  {
                              "pourquoi":  "Ce duo réunit deux pôles d\u0027un même axe : la Catalyseur·rice Social·e veille au lien, à la cohésion et au climat de confiance, tandis que le·la Pilote Orienté·e Tâche maintient le cap sur les objectifs, les résultats et les délais (Blake \u0026 Mouton, 1964). Chacun protège ce que l\u0027autre risque d\u0027oublier : l\u0027un rappelle que les équipes performent mieux quand chacun s\u0027y sent en sécurité (Edmondson, 2019), l\u0027autre que le soin apporté aux personnes doit aussi déboucher sur des décisions claires et tenues. Ensemble, ils peuvent porter à la fois l\u0027humain et l\u0027avancement concret du travail.",
                              "frictions":  "Le·la Pilote peut percevoir l\u0027attention au relationnel comme une lenteur ou un évitement de la décision, alors que la Catalyseur·rice peut vivre la pression sur les délais comme une mise à mal du collectif. Des malentendus naissent souvent du rythme et des priorités implicites : terminer vite contre prendre soin du lien. Sans explicitation, chacun peut interpréter l\u0027intention de l\u0027autre à travers son propre pôle et durcir sa position.",
                              "collaborer":  "Une répartition simple aide : le·la Pilote cadre l\u0027objectif, le périmètre et l\u0027échéance, la Catalyseur·rice s\u0027assure de l\u0027adhésion, de la circulation de la parole et du climat qui permet de tenir ce cadre. Convenez à l\u0027avance des moments dédiés à la décision et de ceux dédiés à l\u0027écoute, pour éviter qu\u0027ils se télescopent. Une relecture croisée avant chaque jalon — « est-ce clair ? » et « est-ce que chacun suit ? » — sécurise à la fois le résultat et les personnes.",
                              "developper":  {
                                                 "catalyseur":  "En tant que Catalyseur·rice Social·e, énoncez vous-même l\u0027objectif concret et l\u0027échéance en début de réunion, puis clôturez les échanges par une décision explicite : nommer « ce que nous décidons et pour quand » donne un appui tangible au lien que vous cultivez.",
                                                 "pilote":  "En tant que Pilote Orienté·e Tâche, ouvrez vos points de travail par une brève prise de température et vérifiez, avant d\u0027avancer, que chacun a pu s\u0027exprimer ; ces quelques minutes consacrées au vécu de l\u0027équipe sécurisent souvent la tenue des délais que vous visez (Edmondson, 2019)."
                                             }
                          },
    "pilote|pionnier":  {
                            "pourquoi":  "Ces deux profils relèvent d\u0027axes distincts et se combinent plutôt qu\u0027ils ne s\u0027opposent : le Pilote Orienté·e Tâche apporte le cadre, la clarté des objectifs et la tenue des délais, tandis que le Pionnier·ère Adaptatif·ive ouvre l\u0027horizon, propose des pistes nouvelles et porte le changement. L\u0027un convertit l\u0027élan en résultats concrets, l\u0027autre empêche le cadre de se figer et alimente l\u0027équipe en idées (Kirton, 2003). C\u0027est précisément cette tension entre exécution structurée et exploration qui rend le duo fécond.",
                            "frictions":  "Le Pilote peut percevoir les nouvelles propositions comme des digressions qui menacent le planning, et le Pionnier peut vivre l\u0027insistance sur les délais comme un frein à l\u0027expérimentation. Le premier valorise « faire aboutir », le second « explorer autrement », ce qui crée des malentendus sur ce qui compte vraiment à un moment donné. Sans clarification, chacun peut interpréter la priorité de l\u0027autre comme un manque de sérieux ou de souplesse.",
                            "collaborer":  "Distinguez explicitement les temps d\u0027exploration et les temps d\u0027exécution : le Pionnier·ère ouvre les options en amont, le Pilote cadre ensuite la mise en œuvre et le suivi. Convenez ensemble de critères simples pour décider quand une idée passe en projet et quand on verrouille le périmètre, afin que la nouveauté nourrisse l\u0027objectif sans le diluer. Un sas court (« on teste à petite échelle avant de généraliser ») permet souvent de réconcilier prudence opérationnelle et envie d\u0027innover.",
                            "developper":  {
                                               "pilote":  "Réservez de courtes plages pour examiner une alternative avant de figer le plan, et accueillez au moins une idée « hors cadre » par projet sans la juger immédiatement sur sa faisabilité.",
                                               "pionnier":  "Choisissez une de vos idées et donnez-lui un objectif concret, une première étape et une échéance, pour transformer l\u0027élan exploratoire en résultat visible par l\u0027équipe."
                                           }
                        },
    "pilote|stabilisateur":  {
                                 "pourquoi":  "Ces deux profils relèvent d\u0027axes différents, ce qui les rend très combinables : le Pilote Orienté·e Tâche fixe le cap, structure les objectifs et tient les délais, tandis que le Stabilisateur·rice Prudent·e veille à la fiabilité, à la continuité et à la solidité de ce qui existe déjà. Là où l\u0027un imprime le mouvement et la clarté du résultat, l\u0027autre sécurise l\u0027exécution dans la durée et limite les angles morts opérationnels. Ensemble, ils peuvent transformer une intention en résultat tenable, en mariant énergie de pilotage et ancrage pragmatique (Blake \u0026 Mouton, 1964).",
                                 "frictions":  "Le Pilote peut percevoir la prudence du Stabilisateur comme un frein ou un excès de précautions, tandis que le Stabilisateur peut vivre la pression des délais comme une précipitation qui fragilise la qualité. Les rythmes diffèrent : l\u0027un veut avancer vite et trancher, l\u0027autre veut consolider avant d\u0027engager. Sans explicitation, ces écarts se lisent comme un manque d\u0027implication d\u0027un côté ou un manque de rigueur de l\u0027autre, alors qu\u0027il s\u0027agit surtout de priorités complémentaires.",
                                 "collaborer":  "Confiez au Pilote le cadrage des objectifs, la priorisation et le suivi des échéances, et au Stabilisateur la sécurisation des process, l\u0027anticipation des risques d\u0027exécution et la qualité dans la durée. Convenez ensemble, en amont, d\u0027un seuil de validation : ce qui doit être consolidé avant de lancer, et ce qui peut être ajusté en cours de route. Réservez un court temps d\u0027échange régulier où le Stabilisateur signale les points de vigilance et le Pilote arbitre les priorités, pour que la prudence nourrisse la décision plutôt que de la ralentir.",
                                 "developper":  {
                                                    "pilote":  "Avant de lancer une action, prenez l\u0027habitude d\u0027identifier un ou deux points de continuité à préserver et de demander au Stabilisateur où se situent les risques d\u0027exécution. Intégrer ces vérifications en amont fait souvent gagner du temps en évitant des reprises ultérieures.",
                                                    "stabilisateur":  "Pour un sujet à enjeu, fixez-vous explicitement un objectif et une échéance, et distinguez ce qui mérite vraiment d\u0027être consolidé de ce qui peut avancer en l\u0027état. S\u0027autoriser à trancher plus tôt, sur les points à faible risque, libère de l\u0027énergie pour soigner ce qui compte le plus."
                                                }
                             },
    "catalyseur|pionnier":  {
                                "pourquoi":  "Ces deux profils appartiennent à des axes distincts et se renforcent mutuellement : le ou la Catalyseur·rice Social·e crée le climat de confiance et la cohésion qui permettent au groupe d\u0027oser, tandis que le ou la Pionnier·ère Adaptatif·ive apporte l\u0027élan vers la nouveauté et la capacité à faire bouger les habitudes. L\u0027énergie du changement a d\u0027autant plus de chances d\u0027aboutir qu\u0027elle se déploie dans un cadre relationnel sécurisant, et la sécurité psychologique gagne en utilité quand elle sert un projet d\u0027évolution (Edmondson, 2019). Ensemble, ils combinent le « comment on avance ensemble » et le « vers quoi on avance ».",
                                "frictions":  "Le ou la Pionnier·ère peut percevoir l\u0027attention portée à l\u0027écoute et au consensus comme un frein qui ralentit le changement, tandis que le ou la Catalyseur·rice peut vivre l\u0027enthousiasme pour la nouveauté comme une mise en tension de l\u0027équilibre du groupe ou des liens patiemment tissés. Ces malentendus tiennent souvent à des priorités temporelles différentes : préserver la relation maintenant ou ouvrir une voie nouvelle. Nommer cette différence de tempo évite qu\u0027elle ne se transforme en procès d\u0027intention.",
                                "collaborer":  "Une répartition lisible aide beaucoup : laissez le ou la Pionnier·ère proposer et explorer les pistes de changement, et le ou la Catalyseur·rice veiller à embarquer les personnes concernées, recueillir les réticences et entretenir la cohésion au fil du parcours. Convenez ensemble du rythme et des moments d\u0027écoute avant de lancer une nouveauté, pour que l\u0027innovation soit portée par le collectif plutôt que subie. Cette alliance entre élan et liant donne des changements à la fois ambitieux et acceptés.",
                                "developper":  {
                                                   "catalyseur":  "Vous pouvez vous autoriser, de temps à autre, à proposer vous-même une idée nouvelle ou une façon différente de faire, sans attendre le consensus complet. Voyez le changement non comme une menace pour les liens, mais comme une occasion d\u0027engager le groupe autour d\u0027un projet partagé.",
                                                   "pionnier":  "Avant de lancer une nouveauté, prenez un court temps pour écouter ce que chacun en ressent et reconnaître les attaches aux façons de faire actuelles. Vous constaterez souvent qu\u0027une idée portée par le groupe avance plus loin qu\u0027une idée imposée, même excellente."
                                               }
                            },
    "catalyseur|stabilisateur":  {
                                     "pourquoi":  "Ces deux profils se situent sur des axes différents et se combinent plutôt qu\u0027ils ne s\u0027opposent : le ou la Catalyseur·rice Social·e tisse le lien, la confiance et la sécurité psychologique qui permettent à un collectif de se parler vraiment (Edmondson, 2019), tandis que le ou la Stabilisateur·rice Prudent·e apporte la fiabilité, la continuité et l\u0027ancrage concret qui transforment les bonnes intentions en résultats tenus dans la durée. L\u0027un·e ouvre l\u0027énergie relationnelle et la circulation des idées, l\u0027autre garantit que ce qui est décidé sera réellement consolidé et entretenu. Ensemble, ils offrent à une équipe à la fois la chaleur du climat et la solidité des fondations.",
                                     "frictions":  "La tension la plus fréquente porte sur le rythme et la priorité : la personne Catalyseur·rice peut percevoir le souci de prudence comme un frein ou un manque d\u0027enthousiasme, tandis que la personne Stabilisateur·rice peut vivre l\u0027animation relationnelle comme une dépense d\u0027énergie au détriment du concret à sécuriser. Des malentendus peuvent aussi naître autour de la décision, l\u0027une privilégiant l\u0027adhésion et le climat du groupe, l\u0027autre la robustesse de l\u0027existant et l\u0027absence de risque inutile.",
                                     "collaborer":  "Une répartition fluide consiste à laisser le ou la Catalyseur·rice ouvrir les échanges, recueillir l\u0027adhésion et entretenir le climat, puis à confier au ou à la Stabilisateur·rice la mise en œuvre, le suivi et la fiabilisation de ce qui a été convenu. Il est utile de rendre explicites les deux temps — d\u0027abord faire circuler les idées et écouter, ensuite trancher et consolider — pour que chacun·e reconnaisse l\u0027apport de l\u0027autre plutôt que d\u0027y voir un obstacle. Un point régulier court, où l\u0027on relie l\u0027humeur du collectif aux engagements concrets, aide à tenir ensemble lien et continuité.",
                                     "developper":  {
                                                        "catalyseur":  "Vous pouvez emprunter un peu de l\u0027ancrage du ou de la Stabilisateur·rice en formalisant après vos échanges qui fait quoi et pour quand, et en gardant une trace simple des engagements pris afin que l\u0027énergie partagée se transforme en résultats durables.",
                                                        "stabilisateur":  "Vous pouvez cultiver un peu du mode relation du ou de la Catalyseur·rice en consacrant quelques minutes, avant d\u0027entrer dans le concret, à prendre des nouvelles et à expliciter le sens de ce que vous sécurisez, ce qui renforce l\u0027adhésion autour de votre fiabilité."
                                                    }
                                 },
    "pionnier|stabilisateur":  {
                                   "pourquoi":  "Ces deux profils occupent les pôles opposés d\u0027un même axe, le rapport à la nouveauté, ce qui les rend naturellement complémentaires : le Pionnier ouvre des pistes, explore et propose des manières de faire différentes, tandis que le Stabilisateur teste leur solidité, les ancre dans l\u0027existant et veille à la continuité du service. Cette tension entre exploration et consolidation est précisément ce qui permet à un projet d\u0027avancer sans se disperser ni s\u0027immobiliser (Kirton, 2003). L\u0027un apporte l\u0027élan et l\u0027imagination de nouvelles options, l\u0027autre la fiabilité et le sens du concret qui les rendent durables.",
                                   "frictions":  "Le Pionnier peut percevoir la prudence du Stabilisateur comme un frein ou un manque d\u0027enthousiasme, tandis que le Stabilisateur peut vivre l\u0027appétit de changement comme une remise en cause permanente d\u0027un fonctionnement qui marche. Les désaccords portent souvent moins sur le fond que sur le rythme : l\u0027un voudrait avancer vite et ajuster en chemin, l\u0027autre préfère sécuriser chaque étape avant de bouger. Sans dialogue, chacun peut interpréter la posture de l\u0027autre comme de l\u0027entêtement plutôt que comme une contribution.",
                                   "collaborer":  "Confiez au Pionnier la phase d\u0027exploration et de génération d\u0027idées, et au Stabilisateur leur mise à l\u0027épreuve, leur cadrage et leur déploiement concret dans la durée. Prévoyez un temps explicite où les nouvelles propositions sont énoncées sans être immédiatement jugées, puis un second temps où elles sont examinées sous l\u0027angle des risques et de la faisabilité (Edmondson, 2019). Nommer ouvertement « ici on diverge, là on converge » évite que l\u0027un freine trop tôt ou que l\u0027autre s\u0027emballe trop vite.",
                                   "developper":  {
                                                      "pionnier":  "Avant de lancer une nouvelle idée, prenez l\u0027habitude de noter ce qui fonctionne déjà bien et que vous tenez à préserver, puis identifiez une ou deux étapes concrètes de mise en œuvre. Vous gagnerez en crédibilité en montrant que la nouveauté que vous proposez s\u0027appuie sur du solide plutôt que de tout repartir de zéro.",
                                                      "stabilisateur":  "Réservez-vous régulièrement un court moment pour vous demander « et si on essayait autrement ? » sur un point précis, sans engagement immédiat. Vous pouvez aussi tester une nouveauté à petite échelle, sur une période limitée, pour l\u0027évaluer sans mettre en jeu l\u0027ensemble de l\u0027existant."
                                                  }
                               }
};
